### ISSUE TITLE
.env file questions

### ISSUE THREAD

**Issue by j2l** [phonetworks/graphjs-server#80]
Hello again,

OK, I think I'm getting to the end of the install.
But you don't say what to do with the .env file when run locally.

My neo4j comes without password.
Can I change .env to INDEX_URI="bolt://localhost:7474";

Bonus question: how to install php eio extension on ubuntu?

Thanks!

**Comment by j2l** [comment]
Hello,
Can you help me on making it work?
Thank you :smile:

**Comment by esokullu** [comment]
You must set up a password on Neo4J
See:
* https://neo4j.com/docs/operations-manual/current/configuration/set-initial-password/#:~:text=Use%20the%20set%2Dinitial%2Dpassword,database%20for%20the%20first%20time.&text=Set%20the%20password%20for%20the,database%20for%20the%20first%20time.
* https://community.neo4j.com/t/how-to-change-password/13562

**Comment by j2l** [comment]
OK, my bad. thank you. I'll try that.

**Comment by esokullu** [comment]
Great, let us know how it works for you.

**Comment by j2l** [comment]
Thank you @esokullu 
The password went through!

But now at `php7.3 run.php`  I get (full message below):
```
calculating headers:
PhoNetworksAutogenerated\User
[2020-06-14 19:32:19] default.INFO: Services set up. Root seed begins. [] []
[2020-06-14 19:32:19] default.INFO: Creating a new graph from scratch [] []
[2020-06-14 19:32:19] default.INFO: Touching 4c2ca3d108156c6d979ed3510fd3f5c3 [] []
[2020-06-14 19:32:19] default.INFO: About to serialize the node  4c2ca3d108156c6d979ed3510fd3f5c3, a user [] []
[2020-06-14 19:32:19] default.INFO: Indexing 4c2ca3d108156c6d979ed3510fd3f5c3 [] []
[2020-06-14 19:32:19] default.INFO: Index request received by 4c2ca3d108156c6d979ed3510fd3f5c3, a user. [] []
[2020-06-14 19:32:19] default.INFO: The query will be as follows; MERGE (n:user {udid: {udid}}) SET n = {data} with data  [] []
PHP Fatal error:  Uncaught GraphAware\Bolt\Exception\HandshakeException: Handshake Exception. Unable to negotiate a version to use. Proposed versions were [1,0,0,0] in /opt/graphjs-server/vendor/graphaware/neo4j-bolt/src/Driver.php:165
Stack trace:
#0 /opt/graphjs-server/vendor/graphaware/neo4j-bolt/src/Driver.php(151): GraphAware\Bolt\Driver->throwHandshakeException('Handshake Excep...')
#1 /opt/graphjs-server/vendor/graphaware/neo4j-bolt/src/Driver.php(115): GraphAware\Bolt\Driver->handshake()
#2 /opt/graphjs-server/vendor/graphaware/neo4j-php-client/src/Connection/Connection.php(192): GraphAware\Bolt\Driver->session()
#3 /opt/graphjs-server/vendor/graphaware/neo4j-php-client/src/Connection/Connection.php(109): GraphAware\Neo4j\Client\Connection\Connection->checkSession()
#4 /opt/graphjs-server/vendor/graphaware/neo4j-php-client/src/Client.php(67): GraphAware\Neo4j\Client\Connection\Connection->run('MERGE (n:user {...', Array, NULL)
#5 /opt/graphjs-server/vendor/pho-adapters/index-neo4j/Neo4j.php(165): GraphAware\Neo4j\Clien in /opt/graphjs-server/vendor/graphaware/neo4j-bolt/src/Driver.php on line 165
'/opt/graphjs-server/vendor/pho-adapters/index-neo4j/QueryResult.php''/opt/graphjs-server/vendor/pho-recipes/web/.compiled/User.php'Logger is not available yet
```
I dont get what is wrong.
