### ISSUE TITLE
uploadFile error on Heroku instance

### ISSUE THREAD

**Issue by esokullu** [phonetworks/graphjs-server#81]
reported by a user:

```
Access to XMLHttpRequest at 'https://kalara.herokuapp.com//uploadFile?public_id=50C228DC-6FDF-42CA-B43F-174687CE2DFC' from origin 'https://chisamui.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

graph.js:1 POST https://kalara.herokuapp.com//uploadFile?public_id=50C228DC-6FDF-42CA-B43F-174687CE2DFC net::ERR_FAILED

 

When attempting to change Profile settings get following error when select to view logged in Profile from my web page?

 

graph.js:1 GET https://phostream.herokuapp.com/v1.0/enrich/feed/user/416b53ea43f22be379c8e1c9f9d373a5/?api_key=50C228DC-6FDF-42CA-B43F-174687CE2DFC&location=unspecified 401 (Unauthorized)

(anonymous) @ graph.js:1

n @ graph.js:1

(anonymous) @ graph.js:1

o @ graph.js:1

get @ graph.js:1

get @ graph.js:1

(anonymous) @ graph.js:1

(anonymous) @ graph.js:1

(anonymous) @ graph.js:1

Promise.then (async)

s @ graph.js:1

t.default @ graph.js:1

o @ graph.js:1

t.default @ graph.js:1

r.tag2.handleContent @ graph.js:1

(anonymous) @ graph.js:1

(anonymous) @ graph.js:1

t.default @ graph.js:1

r.tag2.handleUser @ graph.js:1

(anonymous) @ graph.js:1

value @ graph.js:1

(anonymous) @ graph.js:1

reduce.r @ graph.js:1

Me @ graph.js:1

ee @ graph.js:1

Te @ graph.js:1

update @ graph.js:1

Me @ graph.js:1

ee @ graph.js:1

Te @ graph.js:1

(anonymous) @ graph.js:1

reduce.r @ graph.js:1

(anonymous) @ graph.js:1

reduce.r @ graph.js:1

st @ graph.js:1

e @ graph.js:1

Pe @ graph.js:1

(anonymous) @ graph.js:1

value @ graph.js:1

it @ graph.js:1

(anonymous) @ graph.js:1

reduce.r @ graph.js:1

st @ graph.js:1

e @ graph.js:1

Pe @ graph.js:1

t.default @ graph.js:1

t.default @ graph.js:1

t.default @ graph.js:1

r.tag2.handleShow @ graph.js:1

we @ graph.js:1

Show 19 more frames

graph.js:1 r.StreamApiError {error: {…}, response: XMLHttpRequest, message: "{"message":"Invalid token exception"} with HTTP status code 401", stack: "Error: {"message":"Invalid token exception"} with …change (https://graphjs.com/v2/graph.js:1:604784)"}
```

**Comment by Skorefin** [comment]
When accessing Profile using Heroku instance also get following;

Failed to load resource: the server responded with a status of 401 (Unauthorized)
graph.js:1 r.StreamApiErrorerror: {message: "Invalid token exception"}message: "{"message":"Invalid token exception"} with HTTP status code 401"response: XMLHttpRequest {seq_id: 3, id: "3: GET https://phostream.herokuapp.com/v1.0/enrich…-6FDF-42CA-B43F-174687CE2DFC&location=unspecified", _id: "3: GET https://phostream.herokuapp.com/v1.0/enrich…-6FDF-42CA-B43F-174687CE2DFC&location=unspecified", timeoutTimer: 108, statusCode: 401, …}stack: "Error: {"message":"Invalid token exception"} with HTTP status code 401↵    at r.StreamApiError.i (https://graphjs.com/graph.js:1:34066)↵    at new r.StreamApiError (https://graphjs.com/graph.js:1:34448)↵    at Object.callback (https://graphjs.com/graph.js:1:905747)↵    at https://graphjs.com/graph.js:1:604760↵    at XMLHttpRequest.t.onreadystatechange (https://graphjs.com/graph.js:1:604784)"__proto__: Error
graph.js:1 GET https://phostream.herokuapp.com/v1.0/enrich/feed/user/416b53ea43f22be379c8e1c9f9d373a5/?api_key=50C228DC-6FDF-42CA-B43F-174687CE2DFC&location=unspecified 401 (Unauthorized)
(anonymous) @ graph.js:1
n @ graph.js:1
(anonymous) @ graph.js:1
o @ graph.js:1
get @ graph.js:1
get @ graph.js:1
(anonymous) @ graph.js:1
(anonymous) @ graph.js:1
(anonymous) @ graph.js:1
Promise.then (async)
s @ graph.js:1
t.default @ graph.js:1
o @ graph.js:1
t.default @ graph.js:1
handleContent @ graph.js:1
(anonymous) @ graph.js:1
(anonymous) @ graph.js:1
(anonymous) @ graph.js:1
(anonymous) @ graph.js:1
Promise.then (async)
s @ graph.js:1
t.default @ graph.js:1
(anonymous) @ graph.js:1
t.default @ graph.js:1
(anonymous) @ graph.js:1
t.default @ graph.js:1
handleUser @ graph.js:1
(anonymous) @ graph.js:1
value @ graph.js:1
(anonymous) @ graph.js:1
reduce.r @ graph.js:1
Me @ graph.js:1
ee @ graph.js:1
Te @ graph.js:1
update @ graph.js:1
Me @ graph.js:1
ee @ graph.js:1
Te @ graph.js:1
(anonymous) @ graph.js:1
reduce.r @ graph.js:1
(anonymous) @ graph.js:1
reduce.r @ graph.js:1
st @ graph.js:1
e @ graph.js:1
Pe @ graph.js:1
(anonymous) @ graph.js:1
value @ graph.js:1
it @ graph.js:1
(anonymous) @ graph.js:1
reduce.r @ graph.js:1
st @ graph.js:1
e @ graph.js:1
Pe @ graph.js:1
t.default @ graph.js:1
t.default @ graph.js:1
t.default @ graph.js:1
r.tag2.handleShow @ graph.js:1
we @ graph.js:1
Show 26 more frames
graph.js:1 r.StreamApiError {error: {…}, response: XMLHttpRequest, message: "{"message":"Invalid token exception"} with HTTP status code 401", stack: "Error: {"message":"Invalid token exception"} with …atechange (https://graphjs.com/graph.js:1:604784)"}
